export const CALANDER_REQUEST='CALANDER_REQUEST'
export const CALANDER_SUCCESS='CALANDER_SUCCESS'
export const CALANDER_FAIL='CALANDER_FAIL'

export const ETAT_INVOICE_REQUEST='ETAT_INVOICE_REQUEST'
export const ETAT_INVOICE_SUCCESS='ETAT_INVOICE_SUCCESS'
export const ETAT_INVOICE_FAIL='ETAT_INVOICE_FAIL'